---
deployment:
  tasks:
    # - export DEPLOYPATH=/home/kina3126/public_html/kanzupermaiabadi.co.id/
    # - export DEPLOYPATH=/home/kina3126/public_html/altonpermaiabadi.co.id/
    - export DEPLOYPATH=/home/kina3126/public_html/alamkautsarsejahtera.co.id/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader
    